
const SET_ONEDOCTOR = 'SET_ONEDOCTOR'
const ADD_DOCTOR = 'ADD_DOCTOR'
const CLEAR_DOCTOR = 'CLEAR_DOCTOR'
const ADD_FEEDBACK = 'ADD_FEEDBACK'

export {
  ADD_DOCTOR,
  SET_ONEDOCTOR,
  CLEAR_DOCTOR,
  ADD_FEEDBACK
}
