const SET_EVENTS = 'SET_EVENTS'
const ADD_EVENT = 'ADD_EVENT'
const GET_ONE_EVENT = "GET_ONE_EVENT"
const CLEAR_EVENT = 'CLEAR_EVENT'
const DELETE_EVENT ="DELETE_EVENT"
const SORT_DATE_EVENT ="SORT_DATE_EVENT"

export {
  SET_EVENTS,
  ADD_EVENT,
  GET_ONE_EVENT,
  CLEAR_EVENT,
  DELETE_EVENT,
  SORT_DATE_EVENT
}
