const SET_HISTORY = "SET_HISTORY"
const ADD_HISTORY = "ADD_HISTORY"
const CLEAR_HISTORY = 'CLEAR_HISTORY'
const FILTER_PRICE_HISTORY = "FILTER_PRICE_HISTORY "
const FILTER_PROBLEM_HISTORY = "FILTER_PROBLEM_HISTORY"
const SORT_DATE_HISTORY = "SORT_DATE_HISTORY"


export {
  SET_HISTORY,
  ADD_HISTORY,
  CLEAR_HISTORY,
  FILTER_PRICE_HISTORY,
  FILTER_PROBLEM_HISTORY,
  SORT_DATE_HISTORY
}
